# Base Images
## 从天池基础镜像构建
FROM tianchi-bigdata-registry.cn-shanghai.cr.aliyuncs.com/tcc-public/pytorch:2.0.0-py3.9.12-cuda11.8.0-u22.04-cudnn
## 把当前文件夹里的文件构建到镜像的根目录下
ADD ./app /app
ADD ./model /model
# ADD ./tcdata /tcdata
RUN apt update && apt install curl -y
RUN pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --no-cache-dir -r /app/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
## 指定默认工作目录为根目录（需要把run.sh和生成的结果文件都放在该文件夹下，提交后才能运行）
WORKDIR /app
## 镜像启动后统一执行 sh run.sh
CMD ["bash", "run.sh"]